### ISSUE TITLE
Automatic console output

### ISSUE THREAD

**Issue by sbliven** [davidesarra/jupyter_spaces#1]
It would be great if space cells would automatically print their return result similar to a normal cell. Having to use the print statement for output is cumbersome.

**Comment by sbliven** [comment]
I looked into this a little and wanted to share my progress. Cell outputs can be assigned by calling

    self.shell.displayhook(value)

within `SpaceMagick.space`.

However, it seems a bit tricky to get the return value of executing a cell. Right now we're just using `exec`, which does not keep this. The ipython `run_cell` mechanism is doing full AST parsing to get it.

**Comment by davidesarra** [comment]
Hi @sbliven! Thanks for opening this issue and sorry for my delayed reply. I agree. I'd be nice to display the return values of the cells.

We can’t use IPython parsing methods because we need to control the local namespace. However, we can achieve this by letting Jupyter Spaces parse the cell and modify the resulting syntax tree before compiling and executing it.

Later this week I’ll open a PR to improve this behaviour so that it matches what one would expect from IPython.

**Comment by davidesarra** [comment]
I looked more into alternative ways to achieve a "console output" behaviour that matches IPython's. I think we actually can rely on IPython's parsing methods whilst temporarily replacing the IPython user namespace. In this way we can achive virtually perfect feature parity with IPython console outputs (e.g. also tracebacks).

**Comment by davidesarra** [comment]
I'll probably stick with executing the cell interactively (to autmaticaly return the output) without using IPython's shell. I'm not delivering this yet cause I'd like to see if there a solution to address it alongside #2.
